### ISSUE TITLE
Make parser errors readable

### ISSUE THREAD

**Issue by jaseemabid** [jaseemabid/inc#16] opened 2019-06-15 21:03 UTC
`(inc 42` will return: `Error: Error { message: "Error(Code(CompleteByteSlice([40, 105, 110, 99, 32, 52, 50]), Alt))" }`. This is not very useful.

**Comment by vigneshsarma** [comment] 2019-07-27 19:46
Duplicate of #14

**Closed by vigneshsarma** 2019-07-27 19:46 UTC
